apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 1883
      targetPort: mqtt-tcp
      protocol: TCP
      name: mqtt-tcp
    - port: 9001
      targetPort: mqtt-http
      protocol: TCP
      name: mqtt-http
  selector:
    app: {{ template "fullname" . }}